### ISSUE TITLE
Window class names for more tools

### ISSUE THREAD

**Issue by puff** [BaumFX/cpp-anti-debug#1]
x32/x64dbg use the same as IDA Pro (Both are QT applications, and this could cause a lot of false positives)

WindowsForms10.Window.8.app.0.2bf8098_r6_ad1 - Fiddler
Fiddler is a windows form, which means it shares a class name with a lot of other windows forms apps
To bypass fiddler, set the proxy to null before sending an http request

XTPMainFrame - HTTPDebugger
SunAwtFrame - Charles Web Debugging Proxy
these are also shared by other programs

using class names can cause a lot of false positives though

**Comment by BaumFX** [comment]
I'd rather get a lot of false positives than have someone easily bypass it by just changing the process name or window title.

Of course you are right about the QT window class name, but that's just how it is - I cannot change much about that without giving up some of the security.

The "SunAwtFrame" is already in the list because of the detection of Ghidra, I will add the "XTPMainFrame" in the next update (probably tomorrow).

Thank you for your suggestions.
